language: csharp
solution: src/Wetonomy.sln
sudo: required
dist: xenial
mono: none
dotnet: 2.2

install:
  - dotnet restore src/TokenSystem/TokenSystem.csproj
  - dotnet restore src/TokenSystem.Tests/TokenSystem.Tests.csproj

script:
  - dotnet build src/TokenSystem/TokenSystem.csproj
  - dotnet build src/TokenSystem.Tests/TokenSystem.Tests.csproj
  - dotnet test src/TokenSystem.Tests/TokenSystem.Tests.csproj